// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "nft-card": {
      name: "nft-card",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/nft-card")),
      files: ["registry/default/ui/nft-card.tsx"],
    },
    "collection": {
      name: "collection",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/collection")),
      files: ["registry/default/ui/collection.tsx"],
    },
    "nft-card-demo": {
      name: "nft-card-demo",
      type: "components:example",
      registryDependencies: [""],
      component: React.lazy(() => import("@/registry/default/example/nft-card-demo")),
      files: ["registry/default/example/nft-card-demo.tsx"],
    },
    "collection-demo": {
      name: "collection-demo",
      type: "components:example",
      registryDependencies: [""],
      component: React.lazy(() => import("@/registry/default/example/collection-demo")),
      files: ["registry/default/example/collection-demo.tsx"],
    },
  },
}
